# Generated by Django 6.0 on 2026-02-23 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='trabalhos/', verbose_name='Imagem')),
                ('destaque', models.BooleanField(default=True, verbose_name='Mostrar na Galeria')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.servico', verbose_name='Serviço Relacionado')),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
                'ordering': ['-ordem', '-data_criacao'],
            },
        ),
    ]
